algoritmo "Funcao"
// Função :
// Autor :
// Data : 26/11/2020
// Seção de Declarações 

 
funcao divisao ( y,z :inteiro) : inteiro
var
rest : inteiro

inicio

rest <- (y div z)
retorne rest
fimfuncao

var
 a,b, c: real
 
inicio
escreval ("Abaixo insira os numeros para fazer a a divisão!")
escreval()
escreva ("insira uo primeiro numero: ")
leia (a)

escreva ("insira o segindo numero: ")
leia (b)


c <- divisao(a,b)

escreval("O resultado e:",c)



// Seção de Comandos 
fimalgoritmo
